# -*- coding: utf-8 -*-

WORDS = {
    'tormented': 'מיוסר',
    'irrigation': 'השקייה',
    'surveillance': 'השגחה',
    'prosperity': 'שגשוג',
    'contention': 'מחלוקת',
    'probable': 'מסתבר',
    'particular': 'מיוחד',
    'convened': 'התכנס',
    'cultivated': 'מתורבת',
    'evoked': ['גרם', 'עורר'],
    'A succession': 'רצף',
    'hazardous': 'מסוכן',
    'upheaval': 'מהפך',
    'rural': 'כפרי',
    'extensive': 'נרחב',
    'adequate': ['נאות', 'כראוי'],
    'elect': 'לבחור',
    'gracious': 'אדיב',
    'prominent': 'בולט',
    'desolate': ['מבודד', 'שומם'],
    'communal': 'עדתי',
    'rationalize': 'לייעל',
    'relics': 'שרידים מקודשים',
    'eloquate': 'אמן הדיבור',
    'ignorate': 'בור',
    'illiterate': 'בור',
    'reluctant': 'מסרב',
    'affluent': 'עמיד',
    'prevalence': 'שכיחות',
    'astounding': 'מפתיע',
    'preceding': 'קודם',
    'loathed': 'תיעב',
    'mourned': 'התאבל',
    'condemned': 'גינו',
    'great indifference': 'אדישות גדולה',
    'eccentric': 'תמהוני',
    'genial': 'חביב',
    'luminous': ['זורח', 'בוהק'],
    'reigned': 'שלט',
    'pledged': 'התחייב',
    'prominence': 'בולטות',
    'insulation': 'בידוד',
    'negligence': 'רשלנות',
    'flee': 'לברוח',
    'reap': 'לקצור',
    'unearthed': 'נחשף',
    'confiscated': 'מוחרם',
    'hibernated': 'שינה',
    'deteriorated': 'התדרדר',
    'nuisance': 'מטרד',
    'cavity': 'חלל',
    'attire': 'לבוש',
    'icicle': 'נטיף קרח',
    'comprises': 'כולל',
    'condones': ['לסלוח', 'לכפר'],
    'obscene': 'מגונה',
    'courteous': 'אדיב',
    'profound': 'עמוק',
    'lucrative': 'משתלם',
    'immodest': 'לא צנוע',
    'insofar': 'במידה',
    'abduction': 'חטיפה',
    'haze': 'ערפל',
    'feud': 'סכסוך',
    'grime': 'לזהם',
    'crudely': 'בגסות',
    'solely': ['בלבד', 'אך ורק'],
    'regally': 'באופן מלכותי',
    'conveyed': 'מועבר',
    'bewildered': 'נבוך',
    'infant': 'תינוק'
}
